apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Override namespace to prod
namespace: prod

# Reference the base configuration and Traefik resources
resources:
- ../../base
- middleware.yaml
- ingressroute.yaml

# Remove the Istio VirtualService since we're using Traefik IngressRoute
patches:
- target:
    kind: VirtualService
    name: kserve-models-web-app
  patch: |-
    $patch: delete
    apiVersion: networking.istio.io/v1beta1
    kind: VirtualService
    metadata:
      name: kserve-models-web-app

# Override ConfigMap with settings for Traefik IngressRoute with /models prefix
configMapGenerator:
- name: kserve-models-web-app-config
  behavior: replace
  literals:
  - APP_PREFIX=/models
  - APP_DISABLE_AUTH="True"
  - APP_SECURE_COOKIES="False"
  - GRAFANA_PREFIX="/grafana"
  - GRAFANA_CPU_MEMORY_DB="db/knative-serving-revision-cpu-and-memory-usage"
  - GRAFANA_HTTP_REQUESTS_DB="db/knative-serving-revision-http-requests"
